In [1]:
7**4

2401

In [2]:
s="Hii I am Rohan"
s.split()

['Hii', 'I', 'am', 'Rohan']

In [3]:
a="name"
b="Rohan"
print("My {} is {}".format(a,b))

My name is Rohan


In [4]:
import numpy as np

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones(9) *5

array([5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
a=np.ones(9) *5
a.reshape(3,3)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [15]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
np.linspace(0,9,9).reshape(3,3)

array([[0.   , 1.125, 2.25 ],
       [3.375, 4.5  , 5.625],
       [6.75 , 7.875, 9.   ]])

In [34]:
np.arange(1,26)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [35]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
np.arange(1,26).reshape(5,5)[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [40]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
mat=np.arange(1,26).reshape(5,5)

In [55]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [57]:
mat.shape

(5, 5)

In [61]:
np.arange(1,26).reshape(5,5)[4]

array([21, 22, 23, 24, 25])

In [62]:
np.arange(1,26).reshape(5,5)[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
mat.sum()

325

In [64]:
mat.std()

7.211102550927978

In [65]:
mat.sum(axis =0)

array([55, 60, 65, 70, 75])